# Required for GitHub Pages
title: "Achraf Routabi - CV"
description: "Professional CV"
theme: minimal # This is the simplest Jekyll theme that won't interfere

# Disable unwanted Jekyll processing
plugins: []
markdown: kramdown

# Exclude files from processing (keep your raw CSS)
exclude:
  - style.css
